# Generated by Django 4.2 on 2025-01-31 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True, verbose_name='製品コード')),
                ('name', models.CharField(max_length=100, verbose_name='製品名')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='製品単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品一覧',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '入荷'), ('OUT', '出荷')], max_length=3, verbose_name='移動タイプ')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('movement_date', models.DateField(verbose_name='入出荷日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '入出荷',
                'verbose_name_plural': '入出荷一覧',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_code', models.CharField(max_length=20, unique=True, verbose_name='製造コード')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='製造数量')),
                ('order_date', models.DateField(verbose_name='受注日')),
                ('manufacture_deadline', models.DateField(verbose_name='製造期日')),
                ('planned_completion_date', models.DateField(verbose_name='完了予定日')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '生産情報',
                'verbose_name_plural': '生産情報一覧',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫一覧',
            },
        ),
    ]
