# Generated by Django 4.2 on 2024-12-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, unique=True, verbose_name='得意先コード')),
                ('name', models.CharField(max_length=100, verbose_name='得意先名')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '得意先',
                'verbose_name_plural': '得意先一覧',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True, verbose_name='製品コード')),
                ('name', models.CharField(max_length=100, verbose_name='製品名')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='製品単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品一覧',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='受注数量')),
                ('order_date', models.DateField(verbose_name='受注日')),
                ('delivery_date', models.DateField(verbose_name='納品予定日')),
                ('delivery_completed_date', models.DateField(blank=True, null=True, verbose_name='納品完了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='得意先')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '受注',
                'verbose_name_plural': '受注一覧',
            },
        ),
    ]
